version: '3.3'

services:
  domoticz:
    image: domoticz-sma
    container_name: domoticz
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config:/opt/domoticz/userdata
    environment:
      - TZ=Europe/Stockholm
